Repository lionezajoao/trabalho-ps, pull requests merged in 2025-07, with the labels that each got.

#36 feat: refactor game screen and GUI to enhance action menus and event logging; update screen dimensions
  app/src/graphs/game_screen.py
  app/src/graphs/graph_gui.py
  app/src/player.py
Labels: bug

#37 feat: add research station color definition for improved visualization
  app/src/graphs/graph_gui.py
  docs/diagram/class/pandemic_class_diagram.wsd
Labels: bug

#40 Implement game UI and functionality
  .actrc
  .gitignore
  Pandemic.spec
  README.md
  app/__init__.py
  app/main.py
  app/src/__init__.py
  app/src/board.py
  app/src/classes/__init__.py
  app/src/classes/baralho.py
  app/src/classes/board.py
  app/src/classes/cartas.py
  app/src/classes/city.py
  app/src/classes/enums.py
  app/src/classes/gerenciador_descarte.py
  app/src/classes/habilidades.py
  app/src/classes/partida.py
  app/src/classes/personagem.py
  app/src/classes/player.py
  app/src/classes/turno.py
  app/src/graphs/start_screen.py
  app/src/ui/game_screen.py
  app/src/ui/graph_gui.py
  app/src/ui/start_screen.py
  conftest.py
  docs/tests/TESTING_ACTIONS.md
  docs/tests/TESTING_WITH_ACT.md
  install-docker-act.sh
  test-actions.sh
  tests/test_classes.py
Labels: enhancement, help wanted

#41 refactor(diagram): change Tabuleiro-Baralho relationship from composition to association
  docs/diagram/class/pandemic_class_diagram.png
  docs/diagram/class/pandemic_class_diagram.wsd
Labels: documentation

#44 Fixed update executable actions
  .github/workflows/build.yaml
Labels: bug

#45 Adiciona documentação sobre estimativas de Burndown e EVM
  docs/management/README.md
  docs/management/burndown/csv/burndown_daily.csv
  docs/management/burndown/csv/commits_detailed.csv
  docs/management/burndown/img/Burndown_Sprint_0001.jpg
  docs/management/burndown/img/Burndown_Sprint_0002.jpg
  docs/management/burndown/img/Burndown_Sprint_0003.jpg
  docs/management/burndown/img/Burndown_Sprint_0004.jpg
  docs/management/burndown/img/Burndown_Sprint_0005.jpg
  docs/management/burndown/img/Burndown_Sprint_0006.jpg
  docs/management/burndown/img/sprint_burndown.csv
  docs/management/evm/EVM_Analysis.md
  docs/management/evm/csv/evm_detailed.csv
  docs/management/evm/csv/evm_metrics.csv
  docs/management/evm/csv/evm_weekly.csv
  docs/management/evm/img/evm_relatorio_sprint_0001.jpg
  docs/management/evm/img/evm_relatorio_sprint_0002.jpg
  docs/management/evm/img/evm_relatorio_sprint_0003.jpg
  docs/management/evm/img/evm_relatorio_sprint_0004.jpg
  docs/management/evm/img/evm_relatorio_sprint_0005.jpg
  docs/management/evm/img/evm_relatorio_sprint_0006.jpg
Labels: documentation

#47 Possible fix for broken workflow
  .github/workflows/build.yaml
Labels: bug

#48 Fix release artifact path and file detection
  .github/workflows/build.yaml
Labels: bug

#46 Atualiza gráficos de burndown e documentação de gerenciamento de projetos
  docs/management/README.md
  docs/management/burndown/csv/burndown_daily.csv
  docs/management/burndown/img/Burndown_Sprint_0001.jpg
  docs/management/burndown/img/Burndown_Sprint_0002.jpg
  docs/management/burndown/img/Burndown_Sprint_0003.jpg
  docs/management/burndown/img/Burndown_Sprint_0004.jpg
  docs/management/burndown/img/Burndown_Sprint_0005.jpg
  docs/management/burndown/img/Burndown_Sprint_0006.jpg
  docs/management/burndown/img/sprint_burndown.csv
  docs/management/evm/img/evm_relatorio_total.jpeg
Labels: documentation
